#!/usr/bin/env bash
#This script transfers a file from client to server
#takes four parameters
#	The path to the file to be transferred
#	The IP of the server we want to transfer the file to
#	The username scp connects with
#	The path to the SSH private key that scp uses
if [[ $# -lt 3 ]]
then 
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
if [[ $# == 3 ]]
then 
	scp -o "StrictHostKeyChecking no" "${1}" "${3}@${2}":~/
	exit
fi
if [[ $# == 4 ]]
then
	scp -i "${4}" -o "StrictHostKeyChecking no" "${1}" "${3}@${2}":~/
	exit 1
fi
