#!/usr/bin/env bash
#configuring Nginix server so that /redirect_me
#is redirecting to another page
#!/usr/bin/env bash
#this script will install nginx to the web server
#Nginix will listen on port 80
#When querying Nginx at its root / with a GET request (requesting a page)
#using curl, it must return a page that contains the string Hello World!
sudo apt update
sudo apt -y install nginx
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo bash -c 'cat > /etc/nginx/site-available/default << EOF
server {
	listen 80;
	server_name default_server;

	location / {
		root /var/www/html;
		index index.html
	}
	location /redirect_me {
		try_files \$uri \$uri/ =404;
	}
}
EOF'
sudo service nginx start
