#!/usr/bin/env bash
#this script installs nginix on webserver: it listens to port 80:
#creates a redirect to another page
#adss a custom 404 page 

REDIRECT_301="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"
NOTFOUND_404="error_page 404 /custom_404.html;\n\\tlocation = /custom_404.html {\n\t\t root /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
PATTERN="#error_page 404 /404.html;"

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "30i $REDIRECT_301" /etc/nginx/sites-available/default #IT SHOULD BE LINE 30

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "s@$PATTERN@$NOTFOUND_404@" /etc/nginx/sites-available/default

sudo service nginx restart
