#!/usr/bin/env bash
#install nginx on web server listening on port 80
#has a custom 404
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello world' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
service nginx start
