#!/usr/bin/env bash
#install and configure HAproxy on front-end server
#HAproxy should send traffic to web-01 and web-02
#HAproxy is configured by init script
sudo apt -y update
sudo apt install -y haproxy

OUT=/etc/haproxy/haproxy.cfg
  
cat <<EOF >>$OUT
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server 196529-web-01 54.236.16.58 check
   server 196529-web-02 52.86.115.233 check
EOF
echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
