#!/usr/bin/env bash
#shorter code for running nginx as nginx
pkill -f apache2
sed -i s/80/8080/g /etc/nginx/sites-available/default
chmod 666 /etc/nginx/nginx.conf
sudo -su nginx nginx -c /etc/nginx/nginx.conf

